export const FETCH_CURRENT_USER = "FETCH_CURRENT_USER_REQUEST";
export const FETCH_CURRENT_USER_SUCCESS = "FETCH_CURRENT_USER_SUCCESS";
export const FETCH_CURRENT_USER_ERROR = "FETCH_CURRENT_USER_SUCCESS";
