version: '3.3'
services:
  db:
    image: postgres
    container_name: trans-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app

  adminer:
    image: adminer
    container_name: trans-adminer
    ports:
      - "8080:8080"
    networks:
      - app

networks:
  app:
    driver: bridge
